-- Oracle Table Creation to work with Sqoop

CREATE TABLE BOOK_TYPES
            (TYPE_SRL	NUMBER(10)
					  ,TYPES		VARCHAR2(100)
						);
ALTER TABLE BOOK_TYPES ADD CONSTRAINT BOOK_TYPES_PK PRIMARY KEY(TYPE_SRL);

CREATE TABLE BOOKS_MASTER
			(BOOK_ID        NUMBER(20)
      ,ISBN_NO        VARCHAR2(100)
      ,VERSION_NO     VARCHAR2(50)
      ,EDITION_NO     VARCHAR2(50)
			,BOOK_NAME 		  VARCHAR2(500)
			,BOOK_TYPE_SRL  NUMBER(10)	
			,PUBLISHER_NAME VARCHAR2(500)
			,AUTHOR_NAME 	  VARCHAR2(500)
			,ISSUE_DATE		  DATE			
			,RECORD_ACTIVE	CHAR(1) DEFAULT 'Y'
			);
ALTER TABLE BOOKS_MASTER ADD CONSTRAINT BOOKS_MASTER_PK PRIMARY KEY(ISBN_NO,VERSION_NO);
ALTER TABLE BOOKS_MASTER ADD CONSTRAINT BOOKS_MASTER_UK UNIQUE KEY(BOOK_ID);

CREATE TABLE MEMBERS
       (MEMBER_ID             NUMBER(20)
       ,MEMBER_SALUTATION     VARCHAR2(20)
       ,MEMBER_FIRST_NAME     VARCHAR2(200)
       ,MEMBER_MIDDLE_NAME    VARCHAR2(200)
       ,MEMBER_LAST_NAME      VARCHAR2(200)
       ,MEMBER_GENDER         CHAR(1)
       ,MEMBER_MOBILE_NUMBER  VARCHAR2(20)
       ,MEMBER_HOME_PHONE     VARCHAR2(20)
       ,MEMBER_ADDRESS        VARCHAR2(1000)
       ,MEMBER_CREAT_DT       TIMESTAMP
       );
ALTER TABLE MEMBERS ADD CONSTRAINT MEMBERS_PK PRIMARY KEY(MEMBER_ID);

CREATE TABLE BOOKS_ISSUE_DTLS
       (ISSUE_ID       NUMBER(30)
       ,BOOK_ID        NUMBER(20)
       ,MEMBER_ID      NUMBER(20)
       ,ISSUE_DT       DATE
       ,RETURN_DT      DATE
       );
  
CREATE TABLE BOOKS_SENTIMENTAL
       (BOOK_NAME       VARCHAR2(500)
       ,READING_COUNT   NUMBER(10)
       ,FIN_YEAR        VARCHAR2(100)
       );  
      
